# Generated by Django 2.2.3 on 2019-07-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksShare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(db_index=True, default='Unknown', max_length=150),
            preserve_default=False,
        ),
    ]
