# Generated by Django 2.2.3 on 2019-07-26 08:31

import booksShare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksShare', '0002_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=booksShare.models.get_image_path),
        ),
    ]
